[build]
  publish = "public"
  command = ""

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/submit"
  to = "/.netlify/functions/submit"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/fonts/**"]
